# Generated by Django 5.2.9 on 2026-02-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_sesion_minutos', models.IntegerField(default=30, verbose_name='Tiempo de Sesión (min)')),
            ],
        ),
    ]
