# Generated by Django 5.2.9 on 2026-02-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_configuracionglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='tiempo_aviso_minutos',
            field=models.IntegerField(default=1, verbose_name='Avisar antes de finalizar (min)'),
        ),
    ]
