# Generated by Django 5.2.9 on 2026-02-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_configuracionglobal_tiempo_aviso_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='tiempo_afk_visual_minutos',
            field=models.IntegerField(default=1, verbose_name='Considerar AFK tras (min)'),
        ),
    ]
