# Generated by Django 5.2.11 on 2026-02-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_configuracionglobal_tiempo_afk_visual_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('creada_por_admin', models.BooleanField(default=False)),
                ('es_publica', models.BooleanField(default=False)),
                ('autor', models.CharField(default='Anónimo', max_length=50)),
                ('suma_puntuacion', models.IntegerField(default=0)),
                ('cantidad_votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='tiempo_revelacion_segundos',
            field=models.IntegerField(default=5, verbose_name='Tiempo para ver rol (seg)'),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tiempo_afk_visual_minutos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tiempo_aviso_minutos',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tiempo_sesion_minutos',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='PackPalabras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_principal', models.CharField(max_length=100)),
                ('palabra_relacionada_1', models.CharField(max_length=100)),
                ('palabra_relacionada_2', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='juego.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_impostores', models.IntegerField(default=1)),
                ('modo_dificil', models.BooleanField(default=False)),
                ('usar_senuelo', models.BooleanField(default=False)),
                ('senuelo_sabe_rol', models.BooleanField(default=True)),
                ('hermanos_impostores', models.BooleanField(default=True)),
                ('impostor_compulsivo', models.BooleanField(default=False)),
                ('en_curso', models.BooleanField(default=False)),
                ('palabra_secreta_actual', models.CharField(blank=True, max_length=100)),
                ('anfitrion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juego.sesiongamemaster')),
                ('categoria_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juego.categoria')),
            ],
        ),
    ]
