# Generated by Django 5.2.11 on 2026-02-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tiempo_aviso_minutos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='tiempo_sesion_minutos',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='JugadorLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('es_impostor', models.BooleanField(default=False)),
                ('es_senuelo', models.BooleanField(default=False)),
                ('palabra_asignada', models.CharField(blank=True, max_length=100)),
                ('orden_turno', models.IntegerField(default=0)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='juego.partidalocal')),
            ],
        ),
    ]
