# Generated by Django 5.2.11 on 2026-02-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_alter_configuracionglobal_tiempo_aviso_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cantidad_partidas',
            field=models.IntegerField(default=0, verbose_name='Veces Jugada'),
        ),
        migrations.AddField(
            model_name='sesiongamemaster',
            name='estado',
            field=models.CharField(default='Conectado', max_length=20),
        ),
        migrations.AddField(
            model_name='sesiongamemaster',
            name='juego_actual',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
