# Generated by Django 5.2.11 on 2026-02-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0007_categoria_cantidad_partidas_sesiongamemaster_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiongamemaster',
            name='ultimo_impostor_nombre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
