# Generated by Django 5.2.11 on 2026-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0008_sesiongamemaster_ultimo_impostor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionglobal',
            name='min_packs_categoria',
            field=models.IntegerField(default=40, verbose_name='Mínimo packs requeridos'),
        ),
    ]
